# Generated by Django 2.2.16 on 2022-12-09 06:47

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'username не уникально!'}, help_text='Required. 150 characters or fewer.Letters, digits and /-/_ only.', max_length=150, unique=True, validators=[reviews.validators.validate_username], verbose_name='username'),
        ),
    ]
