# Generated by Django 2.2.16 on 2023-02-17 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20221209_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2023, message='Проверьте дату')], verbose_name='Год выпуска'),
        ),
    ]
